print('Hello, What is your name?')
name = input('')
print('Hello ' + name +', Let me get to know you a little better, Tell me about your Favourite meal?')
respond = input ('')
print ('Great, what is your favourite starter?')
starter = input('')
print('And your favourite main course?')
main_course = input('')
print('Great, lastly what about dessert?')
dessert = input('')
print('what is your fourite go to drink?')
drink = input('')      
print('Let me repeat your favourite meal. Your starter would be ' + starter  + ' your main course would be ' + main_course + ' and your favourite dessert is ' + dessert + ' and finally your go to drink is a ' + drink)
print('Now that sounds delish!!')